
onEvent('fluid.registry', event => 
{
    event.create('bone_broth')
    .stillTexture('minecraft:block/water_still')
    .flowingTexture('minecraft:block/water_flow')
    .color(0xDEC07A)
    .displayName('Bone Broth')
    .noBlock()
    event.create('apple_juice')
    .stillTexture('minecraft:block/water_still')
    .flowingTexture('minecraft:block/water_flow')
    .color(0xC68A47)
    .displayName('Apple Juice')
    .noBlock()
    event.create('hot_cocoa')
    .stillTexture('minecraft:block/water_still')
    .flowingTexture('minecraft:block/water_flow')
    .color(0x663931)
    .displayName('Hot Cocoa')
    .noBlock()
    event.create('matcha_tea')
    .stillTexture('minecraft:block/water_still')
    .flowingTexture('minecraft:block/water_flow')
    .color(0x375922)
    .displayName('Matcha Tea')
    .noBlock()
    event.create('matcha_latte')
    .stillTexture('minecraft:block/water_still')
    .flowingTexture('minecraft:block/water_flow')
    .color(0xDCFFB6)
    .displayName('Matcha Latte')
    .noBlock()
    event.create('matcha_berry_latte')
    .stillTexture('minecraft:block/water_still')
    .flowingTexture('minecraft:block/water_flow')
    .color(0xC9776C)
    .displayName('Matcha Berry Latte')
    .noBlock()
    event.create('melon_juice')
    .stillTexture('minecraft:block/water_still')
    .flowingTexture('minecraft:block/water_flow')
    .color(0xE24334)
    .displayName('Melon Juice')
    .noBlock()
})